
name: build

on: 
  push:
    branches:
      - test-code-quality

jobs:
  Testing_Code_Quality: 
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Installing Dependencies
        run: |
          sudo apt-get update && sudo apt-get install build-essential
          sudo apt install cmake -y
          sudo apt install clang clang-tidy clang-format ninja-build -y
          sudo apt install mesa-common-dev libglu1-mesa-dev -y
      
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          aqtversion: '==2.1.*'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{ github.workspace }}/bin/'
          install-deps: 'true'
          archives: 'qttools qtquickcontrols2 qtquickcontrols qtdeclarative qtbase'
          tools: 'tools_cmake tools_ninja tools_generic'

      - name: Build project
        run: |
          export CMAKE_PREFIX_PATH=${{env.Qt5_Dir}}
          export CC=$(which gcc)
          export CXX=$(which gcc++)
          export CURRENT_SOURCE_DIR=$(pwd)
          # printenv
          # cd ${{env.Qt5_Dir}}/bin
          # ls -all
          mkdir build && cd build
          export CURRENT_BUILD_DIR=$(pwd)
          cmake .. -G Ninja
          cmake --build . --config Debug --target all -j $(nproc) --